name: ludyo
description: "The best game-bookmark app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  animations: ^2.1.1
  cached_network_image: ^3.4.1
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

import_sorter:
  comments: false
